name: Test Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig
    - name: npm install, build
      run: |
        # Try npm ci first, fall back to npm install if lock file is out of sync
        npm ci || npm install
        cd editor
        npm ci || npm install
        cd ..
        npm install -g @vscode/vsce
        npm run pack
        mv unotes-*.vsix Unotes-latest.vsix
        
      env:
        CI: true
    - uses: actions/upload-artifact@v4
      with:
        name: Unotes-latest-node${{ matrix.node-version }}
        path: Unotes-latest.vsix
